spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/desafio
    driverClassName: org.postgresql.Driver
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: false

logging:
  level:
    root: INFO
    org.springframework.web: INFO
